package com.ai.ecs.ecm.mall.wap.modules.member.vo;

public class FavoriteGoodsResult
{
    private Long memberFollowId;

    private Long memberId;

    private String memberFollowBusiName;
   
    private String memberFollowBusiUrl;//关注访问路径
   
    private String memberFollowBusiImgUrl;
    
    private Long price;
    
    public Long getPrice()
    {
        return price;
    }

    public void setPrice(Long price)
    {
        this.price = price;
    }

    public Long getMemberFollowId() {
        return memberFollowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_MEMBER_FOLLOW.MEMBER_FOLLOW_ID
     *
     * @param memberFollowId the value for TF_MEMBER_FOLLOW.MEMBER_FOLLOW_ID
     *
     * @mbggenerated Tue Feb 23 16:13:01 CST 2016
     */
    public void setMemberFollowId(Long memberFollowId) {
        this.memberFollowId = memberFollowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_MEMBER_FOLLOW.MEMBER_ID
     *
     * @return the value of TF_MEMBER_FOLLOW.MEMBER_ID
     *
     * @mbggenerated Tue Feb 23 16:13:01 CST 2016
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_MEMBER_FOLLOW.MEMBER_ID
     *
     * @param memberId the value for TF_MEMBER_FOLLOW.MEMBER_ID
     *
     * @mbggenerated Tue Feb 23 16:13:01 CST 2016
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_NAME
     *
     * @return the value of TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_NAME
     *
     * @mbggenerated Tue Feb 23 16:13:01 CST 2016
     */
    public String getMemberFollowBusiName() {
        return memberFollowBusiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_NAME
     *
     * @param memberFollowBusiName the value for TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_NAME
     *
     * @mbggenerated Tue Feb 23 16:13:01 CST 2016
     */
    public void setMemberFollowBusiName(String memberFollowBusiName) {
        this.memberFollowBusiName = memberFollowBusiName == null ? null : memberFollowBusiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_URL
     *
     * @return the value of TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_URL
     *
     * @mbggenerated Tue Feb 23 16:13:01 CST 2016
     */
    public String getMemberFollowBusiUrl() {
        return memberFollowBusiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_URL
     *
     * @param memberFollowBusiUrl the value for TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_URL
     *
     * @mbggenerated Tue Feb 23 16:13:01 CST 2016
     */
    public void setMemberFollowBusiUrl(String memberFollowBusiUrl) {
        this.memberFollowBusiUrl = memberFollowBusiUrl == null ? null : memberFollowBusiUrl.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_IMG_URL
     *
     * @return the value of TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_IMG_URL
     *
     * @mbggenerated Tue Feb 23 16:13:01 CST 2016
     */
    public String getMemberFollowBusiImgUrl() {
        return memberFollowBusiImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_IMG_URL
     *
     * @param memberFollowBusiImgUrl the value for TF_MEMBER_FOLLOW.MEMBER_FOLLOW_BUSI_IMG_URL
     *
     * @mbggenerated Tue Feb 23 16:13:01 CST 2016
     */
    public void setMemberFollowBusiImgUrl(String memberFollowBusiImgUrl) {
        this.memberFollowBusiImgUrl = memberFollowBusiImgUrl == null ? null : memberFollowBusiImgUrl.trim();
    }
}
